<?php

class Extend_Warranty_Block_Adminhtml_Sales_Items_Lead extends Mage_Adminhtml_Block_Sales_Items_Column_Name
{
    /**
     * @return mixed|null
     */

    public function getItem()
    {
        if ($this->getData('item') === null) {
            $this->setItem($this->getParentBlock()->getItem());
        }
        return $this->getData('item');
    }

    public function getOrder()
    {
        return $this->getItem()->getOrder();
    }

    public function getLeadToken($_item)
    {
        if ($_item->getProductType() === Mage_Catalog_Model_Product_Type_Configurable::TYPE_CODE) {
            foreach ($_item->getChildrenItems() as $child) {
                if ($child->getLeadToken()) {
                    $leadToken = $child->getLeadToken();
                }
            }
        } elseif ($_item->getLeadToken()) {
            $leadToken = $_item->getLeadToken();
        }
        return $leadToken;
    }

    public function _toHtml()
    {
        if (!$this->getLeadToken($this->getItem())
            || $this->getItem()->getProductType() == Extend_Warranty_Model_Product_Type::TYPE_CODE) {
            return '';
        }
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}