<?php $_item = $this->getChildItem();
$helper = Mage::helper('warranty/connector');
$_product = $_item->getProduct();
$warrantyHelper = Mage::helper('warranty');
$parentQty = $_item->getParentItem()->getQty();
?>
<dt>
    <p><?= $_product->getName(); ?>(<?= $_product->getSku(); ?>)</p>
</dt>
<dd>
    <div id="extend-offer-<?= $_item->getId() ?>"></div>
    <script type="text/javascript">
        var $j = jQuery.noConflict();
        Extend.config(<?php echo $helper->getJsonConfig()?>);
        Extend.buttons.renderSimpleOffer('#extend-offer-<?= $_item->getId() ?>', {
            referenceId: '<?= $_product->getData('sku') ?>',
            onAddToCart: function (opts) {
                const plan = opts.plan;
                if (plan) {
                    let parentId = "<?= $_item->getOptionByCode('simple_product') ? $_item->getProductId() : '' ?>";
                    let url = "<?= $this->getUrl('adminhtml/warranty/add') ?>";
                    plan.product = '<?= $_product->getData('sku') ?>';
                    plan.qty = <?= $_item->getQty() * $parentQty ?>;

                    <?php if($_item->getProduct()->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE):?>
                        plan.dynamic_sku = "<?= $warrantyHelper->getComplexProductSku($_product);?>";
                    <?php endif;?>

                    $j.get(url, {
                        warranty: plan,
                        option: parentId,
                    }).done(function (data) {
                        if (data.status == "success") {
                            order.productGridAddSelected('{products:{"<?php echo $_item->getId() ?>":1}}')
                        } else {
                            console.log("Oops! There was an error adding the protection plan.");
                        }
                    });
                }
            }
        });
    </script>
</dd>